### ISSUE TITLE
--disable-check-for-updates for CI?

### ISSUE THREAD

**Issue by sagiegurari** [davidB/rust-cargo-make#2]
I see in the docs you state to add the '--disable-check-for-updates' flag, but for CI flows, it is automatically disabled (i detect that its running inside CI and github actions is also supported).
this adds a bit more complexity then needed.

**Comment by davidB** [comment]
I add this option in my azure pipeline September 7th, because I got the check (and the warning).
how cargo-make detect that it's running inside CI ?

**Comment by sagiegurari** [comment]
hmmm strange. checkout my ci_info crate. it checks for env vars to detect.
github actions was a recent addition (although it should work without that code using common env vars) and azure was there for a long time.
its based on the npm ci-info package so same detection config.

**Comment by davidB** [comment]
I updated the README on master, the doc on the marketplace will updated with next release.

Thanks for the feedbacks
