### ISSUE TITLE
Update floating v1 tag to point to the latest release

### ISSUE THREAD

**Issue by vtavernier** [davidB/rust-cargo-make#390]
The current [v1 tag](https://github.com/davidB/rust-cargo-make/releases/tag/v1) points to an old version of the action, [v1.4.2](https://github.com/davidB/rust-cargo-make/releases/tag/v1.4.2).

I think the v1 tag should be updated to point to the latest semver-compatible version, i.e. [v1.9.0](https://github.com/davidB/rust-cargo-make/releases/tag/v1.9.0) to propagate the update.

Otherwise, using the v1 tag will keep triggering issues such as #386.

**Comment by davidB** [comment]
I updated the tag v1. 
If I remember correctly I stopped to update it, because it prevents tool like dependabot to detect the update of the version. If it's confirmed I will stop update the v1 tag and explicitly recommend to use full version

**Comment by vtavernier** [comment]
Thanks! I don't know about Dependabot but I've been using [Renovate](https://github.com/marketplace/renovate) to do the same kind of automated updates Dependabot does.

As far as GitHub Actions versions are concerned, Renovate keeps the versioning "precision" the same on updates. So it will update `v1` to `v2` if a `v2` is released, but leaves it as-is otherwise. This means non-breaking updates are "propagated" by just running the workflow later. More precise versions `vX.Y.Z` get updated as they are released instead.
