### ISSUE TITLE
Not picking up latest version

### ISSUE THREAD

**Issue by sagiegurari** [davidB/rust-cargo-make#4]
I faced this issue and i saw others commented about it as well, that its not picking up the latest version.
I think for some reason, it might hit github api max requests? not sure.
the code itself looks ok, but maybe worth to add some error description and see how we can resolve it by maybe providing a github api key or something.

**Comment by davidB** [comment]
I updated the project to follow new template (and packaging)
I updated the dependencies
I changed the http-client & test about how to retrieve the latest version
I released the version 1.3.0 of the action.

🤞

**Comment by sagiegurari** [comment]
thanks a lot

**Comment by davidB** [comment]
fix doesn't work :-(
```
search latest version of cargo-make
##[warning]request to retrieve latest version of cargo-make failed: [object Object]
installing cargo-make 0.30.7 ...
```

from a build of rust project of mine

**Comment by davidB** [comment]
So the http request to retrieve the latest value failed "randomly" because:
```
      with status: 403
      with message: rate limit exceeded
```

**Comment by sagiegurari** [comment]
ya that's what i figured in my original description. i think its ok maybe to ask for github token? and use it for the http request.
there are many actions asking you for the default github token. 
however, i never developed a gh action :)

**Comment by davidB** [comment]
The version 1.4.1 should use the github token if it's available (implicitly or explicitly) to retrieve the last version.
