### ISSUE TITLE
Node 16 deprecation

### ISSUE THREAD

**Issue by grzegorzkrukowski** [davidB/rust-cargo-make#423]
As [GitHub announced](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) all actions should switch to Node20 by Sprint 2024

**Comment by davidB** [comment]
v1.10 switch to node 20

**Comment by grzegorzkrukowski** [comment]
@davidB should the v1 tag be also moved to point to v1.10 ? It seems it's still pointing to old v1.9.
![CleanShot 2024-02-21 at 14 29 14@2x](https://github.com/davidB/rust-cargo-make/assets/1301068/1f19b517-5e70-41aa-80de-bca1ed1062a4)
